const Projects = [
  {
    name: "Rosie",
    description: "A website for my dog, Rosie to practice Gitlab GraphQL API",
    skills_used: ["JavaScript", "React", "CSS", "HTML", "GraphQL", "Netlify", "Gitlab"],
    prod_link: "https://rosiethebatdog.netlify.app",
    gitlab_link: "https://gitlab.com/elijahsamuels/rosie",
  },
  {
    name: "Wordle-clone",
    description: "A clone of the popular word game, Wordle!",
    skills_used: ["JavaScript", "Node", "CSS", "HTML", "Heroku", "Github"],
    prod_link: "https://wordle-5.netlify.app/",
    github_link: "https://github.com/elijahsamuels/wordle-clone",
  },
  {
    name: "Dru Heller Website",
    description: "A site built for a great musician and educator, Dru Heller.",
    skills_used: ["Gatsby", "JavaScript", "CSS", "HTML", "Netlify", "Github"],
    prod_link: "http://www.druhellermusic.com",
    github_link: "https://github.com/elijahsamuels/druheller",
  },
  {
    name: "QRCode",
    description: "Get your free QR code here!",
    skills_used: [
      "React",
      "React-QRcode",
      "JavaScript",
      "CSS",
      "HTML",
      "Netlify",
      "Github",
    ],
    prod_link: "https://free-qrcode.netlify.app",
    github_link: "https://github.com/elijahsamuels/qrcode",
  },
  {
    name: "Weather App",
    description: "Check the weather a city",
    skills_used: [
      "React",
      "JavaScript",
      "CSS",
      "HTML",
      "Netlify",
      "Github",
    ],
    prod_link: "https://es-weather.netlify.app/",
    github_link: "https://github.com/elijahsamuels/qrcode",
  },
  {
    name: "D3.js",
    description: "Examples visualizing data using D3.js",
    skills_used: [
      "React",
      "JavaScript",
      "D3.js",
      "CSS",
      "HTML",
      "Netlify",
      "Github",
    ],
    prod_link: "https://es-d3js.netlify.app/",
    github_link: "https://github.com/elijahsamuels/d3-starter",
  },
  {
    name: "ElijahSamuels.com",
    description: "Personal website project",
    skills_used: ["React", "JavaScript", "CSS", "HTML", "Netlify", "Github"],
    prod_link: "https://www.elijahsamuels.com",
    github_link: "https://github.com/elijahsamuels/qrcode",
  },
];

export default Projects;